name: GitHub Actions Demo

on: 
  push:
    branches: 
      - main
    paths-ignore: 
      - .github
  pull_request:
    branches: 
      - main
  
  schedule:
    - cron: '15 6 * * 0'
    
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "Job triggered by $github.event_name"
